ERROR - 2022-04-18 09:20:00 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-04-18 09:20:00 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\tokobuku\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tokobuku\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\tokobuku\system\Model.php(728): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tokobuku\app\Models\BookModel.php(27): CodeIgniter\Model->__call('get', Array)
#4 C:\xampp\htdocs\tokobuku\app\Controllers\Book.php(27): App\Models\BookModel->getBook()
#5 C:\xampp\htdocs\tokobuku\system\CodeIgniter.php(832): App\Controllers\Book->index()
#6 C:\xampp\htdocs\tokobuku\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Book))
#7 C:\xampp\htdocs\tokobuku\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tokobuku\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-04-18 09:20:00 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tokobuku\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\tokobuku\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Book), true)
#2 C:\xampp\htdocs\tokobuku\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tokobuku\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\tokobuku\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-04-18 09:20:31 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-04-18 09:20:31 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\tokobuku\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\tokobuku\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\tokobuku\system\Model.php(728): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\tokobuku\app\Models\MajalahModel.php(27): CodeIgniter\Model->__call('get', Array)
#4 C:\xampp\htdocs\tokobuku\app\Controllers\Majalah.php(20): App\Models\MajalahModel->getMajalah()
#5 C:\xampp\htdocs\tokobuku\system\CodeIgniter.php(832): App\Controllers\Majalah->index()
#6 C:\xampp\htdocs\tokobuku\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Majalah))
#7 C:\xampp\htdocs\tokobuku\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tokobuku\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tokobuku\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-04-18 09:20:31 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\tokobuku\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\tokobuku\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Majalah), true)
#2 C:\xampp\htdocs\tokobuku\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\tokobuku\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\tokobuku\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
